import datajoint_plus as djp
from . import h01_auto_proofreading, minnie65_auto_proofreading, minnie65_auto_proofreading_v2

djp.reassign_master_attribute(h01_auto_proofreading)
djp.reassign_master_attribute(minnie65_auto_proofreading)
djp.reassign_master_attribute(minnie65_auto_proofreading_v2)