version: '2'
services:
  notebook:
    image: celiib/mesh_after_party:latest
    build: 
      context: .
    env_file: .env
    environment:
      - DISPLAY=$DISPLAY
      - XSOCK=/tmp/.X11-unix/X0
    ports:
      - "8890:8888"
    volumes:
      - ../notebooks:/notebooks
      - /mnt:/mnt
    container_name: "microns-morphology"

