version: '3.4'

x-shared: &common
  ipc: host
  build:
    context: ../
    dockerfile: Dockerfile
    args: 
      - CLOUDVOLUME_TOKEN=${CLOUDVOLUME_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
  volumes:
    - ../:/src/microns-morphology
    - /mnt:/mnt
  env_file:
    - .env
  container_name: "microns-morphology"

services:
  notebook:
    <<: *common
    ports:
        - "${JUPYTER_HOST:-0.0.0.0}:${JUPYTER_PORT_CONTAINER:-8888}:8888"
    entrypoint: /src/microns-morphology/deploy/entrypoint.sh
    working_dir: /src
  bin:
    <<: *common
    entrypoint: /bin/bash